# CodeScriber options
future1=future1
future2=future2
terminal=gnome-terminal --working-directory\=
filemanager=thunar
previous=no
browser=default
scope=/home
run1=firefox https://www.w3schools.com/
run2=kruler
