const atags = {
	"ajson": "var ajson = [\n	{\"\":\"\"},\n	{\"\":\"\"}\n	];\n",
	"a": "<a href=\"\" id=\"\" target=\"_blank\"></a>",
	"br": "<br style=\"clear:left;\">",
	"button": "<input type=\"button\" onclick=\"\" value=\"\">",
	"checkbox": "<label for='AA'>description</label>\n<input type='checkbox' id='AA' name='postfield' value='postvalue'>",
	"com": "/***\n\n***/\n",
	"echo": "<?php echo '' ?>",
	"getcook": "getCookie(\"\");\n",
    "det": "<details>\n <summary>XXX</summary>\n <p>XXXX</p>\n</details>\n",
	"err": "error_reporting(E_ALL);\nini_set('display_errors', '1');",
	"header": "header(\"Location: \");",
	"html": "<!DOCTYPE HTML>\n<html lang=\"en-US\">\n<head>\n	<meta charset='UTF-8'>\n	<meta name='viewport' content='width=device-width, initial-scale=1'>\n	<title></title>\n</head>\n<body>\n\n</body>\n</html>\n",
	"id": "document.getElementById('')",
	"input": "<input type=\"text\" id=\"\" value=\"\">",
	"ipsum": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus scelerisque sodales condimentum. ",
	"js": "<script type=\"text/javascript\" src=\"../js/myJS-1.2.min.js\"></script>",
	"label": "<label for=\"id\"></label>",
	"link": "<link rel=\"stylesheet\" href=\"\">",
	"man": "<link rel=\"manifest\" href=\"manifest.json\">\n",
	"manifest": "{\n	\"short_name\": \"\",\n	\"name\": \"\",\n	\"icons\": [\n		{\n			\"src\": \".png\",\n			\"sizes\": \"x\",\n			\"type\": \"image/png\"\n		}\n	],\n	\"start_url\": \"index.html\",\n	\"background_color\": \"\",\n	\"theme_color\": \"black\",\n	\"display\": \"standalone\"\n}\n",
	"mdimage": '![alttext](http:// "title")',
	"mdlink": '[linktext](http:// "title")',
	"option": "alert(selobj.options[selobj.selectedIndex].text)",
	"php": "<?php\n\n?>",
	"radio": "<label for='AA'>description</label>\n<input type='radio' id='AA' name='postfield' value='postvalue' checked>",
	"script2": "<script src=\"\"><\/script>",
	"script": "<script>\n\n<\/script>",
	"select": "<select name='' id='' size='' onchange='' autofocus required>\n <option value='' selected>\n <option value=''>\n</select>",
	"setcook": "setCookie(\"name\",\"value\",\"days\");\n",
	"style": "<style>\n\n<\/style>",
	"table": "<style>\ntable, th, td \{\n	border: 1px solid black;\n	margin: auto; /* center */\n}\n\</style>\n\n<table>\n	<tr>\n		<td> </td>\n		<td> </td>\n	</tr>\n	<tr>\n		\<td> </td>\n		<td> </td>\n	</tr>\n</table>\n",
	"ta": "<textarea id=\"\" rows=\"\" cols=\"\" wrap=\"off\"></textarea>",
	"tr": "<tr>\n	<td></td>\n	<td></td>\n</tr>",
	"ul": "<ul>\n <li></li>\n <li></li>\n <li></li>\n <li></li>\n</ul>\n"
};
